// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.488
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Specs.FluentAlerts
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Table")]
    public partial class TableFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Table.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Table", "In order to document the current system state in a human readable format\r\nAs a de" +
                    "veloper\r\nI want to be able to create a hierarchical table of information", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can add normal rows to a table")]
        public virtual void CanAddNormalRowsToATable()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can add normal rows to a table", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given("I have a table");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Cell1",
                        "Cell2"});
            table1.AddRow(new string[] {
                        "One",
                        "1"});
            table1.AddRow(new string[] {
                        "Two",
                        "2"});
#line 8
 testRunner.When("I add the \'normal\' rows", ((string)(null)), table1);
#line 12
  testRunner.And("I build the alert");
#line 13
 testRunner.Then("the alert should have 2 rows");
#line 14
  testRunner.And("row 1 should be a \'normal\' row");
#line 15
  testRunner.And("row 1 cell 1 should be \'One\'");
#line 16
  testRunner.And("row 1 cell 2 should be \'1\'");
#line 17
  testRunner.And("row 2 should be a \'normal\' row");
#line 18
  testRunner.And("row 2 cell 1 should be \'Two\'");
#line 19
  testRunner.And("row 2 cell 2 should be \'2\'");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can add highlighted rows to a table")]
        public virtual void CanAddHighlightedRowsToATable()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can add highlighted rows to a table", ((string[])(null)));
#line 21
this.ScenarioSetup(scenarioInfo);
#line 22
 testRunner.Given("I have a table");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Cell1",
                        "Cell2"});
            table2.AddRow(new string[] {
                        "One",
                        "1"});
#line 23
 testRunner.When("I add the \'highlighted\' rows", ((string)(null)), table2);
#line 26
  testRunner.And("I build the alert");
#line 27
 testRunner.Then("the alert should have 1 rows");
#line 28
  testRunner.And("row 1 should be a \'highlighted\' row");
#line 29
  testRunner.And("row 1 cell 1 should be \'One\'");
#line 30
  testRunner.And("row 1 cell 2 should be \'1\'");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can add header rows to a table")]
        public virtual void CanAddHeaderRowsToATable()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can add header rows to a table", ((string[])(null)));
#line 32
this.ScenarioSetup(scenarioInfo);
#line 33
 testRunner.Given("I have a table");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Cell1"});
            table3.AddRow(new string[] {
                        "One"});
#line 34
 testRunner.When("I add the \'header\' rows", ((string)(null)), table3);
#line 37
  testRunner.And("I build the alert");
#line 38
 testRunner.Then("the alert should have 1 rows");
#line 39
  testRunner.And("row 1 should be a \'header\' row");
#line 40
  testRunner.And("row 1 cell 1 should be \'One\'");
#line 41
  testRunner.And("row 1 should have 1 cells");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can add footer rows to a table")]
        public virtual void CanAddFooterRowsToATable()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can add footer rows to a table", ((string[])(null)));
#line 43
this.ScenarioSetup(scenarioInfo);
#line 44
 testRunner.Given("I have a table");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Cell1"});
            table4.AddRow(new string[] {
                        "One"});
#line 45
 testRunner.When("I add the \'footer\' rows", ((string)(null)), table4);
#line 48
  testRunner.And("I build the alert");
#line 49
 testRunner.Then("the alert should have 1 rows");
#line 50
  testRunner.And("row 1 should be a \'footer\' row");
#line 51
  testRunner.And("row 1 cell 1 should be \'One\'");
#line 52
  testRunner.And("row 1 should have 1 cells");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can create a table with a title")]
        public virtual void CanCreateATableWithATitle()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can create a table with a title", ((string[])(null)));
#line 54
this.ScenarioSetup(scenarioInfo);
#line 55
 testRunner.Given("I create a table with a title \'some title\'");
#line 56
 testRunner.When("I build the alert");
#line 57
 testRunner.Then("the alert should have 2 columns");
#line 58
  testRunner.And("the alert should have 1 rows");
#line 59
  testRunner.And("row 1 should be a \'header\' row");
#line 60
  testRunner.And("row 1 should have 1 cells");
#line 61
  testRunner.And("row 1 cell 1 should be \'some title\'");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can create a table from an objects property values")]
        public virtual void CanCreateATableFromAnObjectsPropertyValues()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can create a table from an objects property values", ((string[])(null)));
#line 63
this.ScenarioSetup(scenarioInfo);
#line 64
 testRunner.Given("I create a table with an object using depth 0");
#line 65
 testRunner.When("I build the alert");
#line 66
 testRunner.Then("the title is the objects type");
#line 67
  testRunner.And("a row is added for each property with cells for property name and property value");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can create a table from an objects property values recursing reference types exce" +
            "pt strings to a given depth")]
        public virtual void CanCreateATableFromAnObjectsPropertyValuesRecursingReferenceTypesExceptStringsToAGivenDepth()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can create a table from an objects property values recursing reference types exce" +
                    "pt strings to a given depth", ((string[])(null)));
#line 69
this.ScenarioSetup(scenarioInfo);
#line 70
 testRunner.Given("I create a table with an object using depth 3");
#line 71
 testRunner.When("I build the alert");
#line 72
 testRunner.Then("the title is the objects type");
#line 73
  testRunner.And("a row is added for each property with cells for property name and property value");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can create a table from an exception")]
        public virtual void CanCreateATableFromAnException()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can create a table from an exception", ((string[])(null)));
#line 75
this.ScenarioSetup(scenarioInfo);
#line 76
 testRunner.Given("I create a table with an exception");
#line 77
 testRunner.When("I build the alert");
#line 78
 testRunner.Then("the table should have a row for the type, message and stack trace for all excepti" +
                    "on in chain");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
